blank_issues_enabled: false # ë¹ˆ ì´ìŠˆ ìƒì„±ì„ ë§‰ìŒ
contact_links:
  - name: ğŸ’¬ í”„ë¡œì íŠ¸ í† ë¡  í¬ëŸ¼
    url: https://github.com/user/repo/discussions # í† ë¡  í¬ëŸ¼ ì£¼ì†Œ
    about: ê¸°ëŠ¥ ì œì•ˆì´ë‚˜ ì§ˆë¬¸ì€ ì´ê³³ì—ì„œ ë…¼ì˜í•´ì£¼ì„¸ìš”.